# Generated by Django 4.2.3 on 2023-07-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='valor_planejado',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
